# Generated by Django 3.2.9 on 2021-11-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=127, null=True)),
                ('text', models.TextField(help_text='Main info..')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(blank=True, max_length=63, null=True, verbose_name='Muellif')),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ('created_at',),
            },
        ),
    ]
