# Generated by Django 3.2.9 on 2021-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=127, null=True)),
                ('blog_subtitle', models.CharField(blank=True, max_length=127, null=True)),
                ('blog_desc', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
            },
        ),
    ]
