# Generated by Django 3.2.9 on 2021-11-08 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('created_at',), 'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
    ]
