# Generated by Django 3.2.9 on 2021-11-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=63, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_tag',
            field=models.ManyToManyField(to='news.Tag'),
        ),
    ]
